### PR TITLE
Added video support for Starboard.

### PR DESCRIPTION
**Pull request by TheOnlyTails**
(the rest of the commits are just to get things to work on my end, don't worry)

### CODE REVIEW

**Comment by saksham4106** [comment]
> the rest of the commits are just to get things to work on my end, don't worry
sus

**Comment by TheOnlyTails** [comment]
What? I had to make sure I had updated files, and that my vcs.xml won't get pushed to the repo, and I did it in a roundabout way. Just look at the changed file and you'll see that I only changed the ``if`` statement checking if the message had an image attached to apply it to videos too.

**Review by Sparky200 — COMMENTED** [review]
Don't change .gitignore unless something really important needs to be removed from the repository.

**Review by Sparky200 — APPROVED** [review]
I don't completely know the code for starboard, but it looks good to me. Are you sure there's support for the starboard embed already built-in?

**Comment by TheOnlyTails** [comment]
It is compatible, since the image is added to the embed by getting the URL, which works the same for video, if I understand correctly.

**Comment by TechnoVisionDev** [comment]
Hmm unfortunately I originally had this if statement in TechnoBot but it didn't seem to embed videos, so I set it to only star images instead. You'll have to find another way to embed videos :(

**Pull request closed without merging**
