### PR TITLE
made "upload" reply with 4 different msgs

### PR DESCRIPTION
**Pull request by C00kieGamez**
to stop people from asking when he will upload, it will now say 4 different msgs

### CODE REVIEW

**Comment by MetalTurtle18** [comment]
Just "upload" is going to get annoying really fast

**Comment by Sparky200** [comment]
> Just "upload" is going to get annoying really fast

Very true. And until the bot is fixed to send messages more than once to each person, this won't work as intended.

**Comment by C00kieGamez** [comment]
just did a ctrl f in general, and 85% of the msgs are asking about the next upload

**Review by Sparky200 — COMMENTED** [review]
Overall, I don't think this will be necessary until the bot is fixed so it responds to people properly. Right now, it only responds to each person once and never responds to them otherwise, and I think that that needs to be fixed first.

**Review by zAG6z — APPROVED** [review]
great changes

**Pull request merged**
