### PR TITLE
add cooldown for automated message replies (extras)

### PR DESCRIPTION
**Pull request by xf8b**
cooldown is 2 minutes

### CODE REVIEW

**Comment by Sparky200** [comment]
I don't know about 2 minutes, but definitely something we need

**Comment by Redstoneguy129** [comment]
I suggest you add a check for moderators. @TechnoVisionDev What do you think of this?

**Comment by xf8b** [comment]
add a check for moderators?

**Comment by Sparky200** [comment]
Override?

**Comment by Redstoneguy129** [comment]
yes, otherwise mods cant do !ban quickly if theres a raid or smth

**Comment by Sparky200** [comment]
Oh, this is only for the "will this work" and "why no work" and stuff

**Comment by Redstoneguy129** [comment]
Also, I see you've copied a lot of your code continuously so maybe at the end of the file you do your put method.

**Comment by Sparky200** [comment]
> no need for `COOLDOWN_MAP.put(authorId, System.currentTimeMillis());` just put at end of everything. if it helps use an if statement.

Problem with this is that it should only run a cooldown if one of the key terms is mentioned. This will make it set the cooldown for ANY message they send

**Comment by Redstoneguy129** [comment]
> 
> 
> > no need for `COOLDOWN_MAP.put(authorId, System.currentTimeMillis());` just put at end of everything. if it helps use an if statement.
> 
> Problem with this is that it should only run a cooldown if one of the key terms is mentioned. This will make it set the cooldown for ANY message they send

thats why i said if statement

**Comment by C00kieGamez** [comment]
sup gamers are we gaming here... i am defiantly an epic gamer and not a 50 year old man

**Pull request merged**
