### PR TITLE
not too really sure about this one idk saw it in a suggestion

### PR DESCRIPTION
**Pull request by saksham4106**

### CODE REVIEW

**Review by Sparky200 — CHANGES_REQUESTED** [review]
This needs a little cleanup:
- EmbedBuilder's methods are stackable allowing for you to do `embed.setTitle("title").setDescription("description")` etc etc.
- EmbedBuilder can be inline as it is not used elsewhere.
- Grammatical Errors
- Overall, the message seems slightly negative and doesn't provide much of a solution to the problem. We don't want people to leave the server and try another, we want them to learn java.

**Review by Sparky200 — COMMENTED** [review]
Excellent! I think the message itself is still a little negative and doesn't really fix the last point in my previous review (it was edited, so that's probably why) but other than that, it looks good.

**Comment by TheOnlyTails** [comment]
Maybe add the links from #programming's pins?

**Comment by TheOnlyTails** [comment]
Maybe add some insiprational stuff about how easy it would be to mod once you know Java?

**Review by xf8b — CHANGES_REQUESTED** [review]
the file is... not a java file?
also formatting ririirir

**Review by Sparky200 — APPROVED** [review]

**Comment by Sparky200** [comment]
I marked as approved, but still waiting on response from the OP what xf8b said.



> the file is... not a java file?
> also formatting ririirir

Make sure to fix this, or I can commit after the PR has been merged.


> Excellent! I think the message itself is still a little negative and doesn't really fix the last point in my previous review (it was edited, so that's probably why) but other than that, it looks good.

This as well, it's better to be nice and use an understanding tone when addressing a community!

**Comment by TechnoVisionDev** [comment]
Nice work, I'm going to alter the message just a bit but I'll be merging what's here, thanks!

**Pull request merged**
